/**
 * HostDaddy.app — Sites content schema.
 *
 * The `sites` table in `schema.ts` is the deployment record (which Cloudflare
 * Pages project, which domain, status). This file adds the *content* layer
 * that customers edit through the Sites module: pages, blog posts, media,
 * forms, contacts, products, orders, email marketing, AI runs.
 *
 * Conventions match `schema.ts`:
 *   - IDs are text (UUIDs generated by callers via crypto.randomUUID())
 *   - All money stored as integer cents in MYR unless otherwise noted
 *   - customer_id denormalized onto every row for fast tenant filtering /
 *     simple ownership checks (each row also references site_id which itself
 *     belongs to a customer; the redundant FK is intentional)
 *   - JSON blobs stored as text — D1 has no native JSON type, parse on read
 *   - Created/updated timestamps via the shared `timestamps` helper
 */

import { sql } from 'drizzle-orm';
import { sqliteTable, text, integer, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
import { customers, sites } from './schema';

// Re-declare helpers to avoid circular import of private statics.
const id = () => text('id').primaryKey();
const timestamps = {
  created_at: integer('created_at', { mode: 'timestamp' })
    .notNull()
    .default(sql`(unixepoch())`),
  updated_at: integer('updated_at', { mode: 'timestamp' })
    .notNull()
    .default(sql`(unixepoch())`),
};

// ─── Pages ───────────────────────────────────────────────────────────────────
// Each site has many pages. Content is stored as a JSON tree of sections/blocks
// matching the visual builder's data model. Rendering and AI tool-calls
// operate on this JSON.

export const sitePages = sqliteTable(
  'site_pages',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    slug: text('slug').notNull(), // '/', '/about', '/contact'
    title: text('title').notNull(),
    content_json: text('content_json').notNull().default('{"sections":[]}'),
    seo_title: text('seo_title'),
    seo_description: text('seo_description'),
    seo_og_image: text('seo_og_image'),
    status: text('status', { enum: ['draft', 'published', 'archived'] })
      .notNull()
      .default('draft'),
    is_home: integer('is_home', { mode: 'boolean' }).notNull().default(false),
    published_at: integer('published_at', { mode: 'timestamp' }),
    ...timestamps,
  },
  (t) => ({
    site_idx: index('site_pages_site_idx').on(t.site_id),
    customer_idx: index('site_pages_customer_idx').on(t.customer_id),
    slug_unique: uniqueIndex('site_pages_site_slug_unique').on(t.site_id, t.slug),
    status_idx: index('site_pages_status_idx').on(t.status),
  }),
);

// ─── Media library ───────────────────────────────────────────────────────────
// Backed by R2 (env.ASSETS). r2_key is the object key, file_name is what the
// user uploaded as. Optional ai_caption + alt_text generated by Workers AI.

export const siteMedia = sqliteTable(
  'site_media',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    r2_key: text('r2_key').notNull(),
    file_name: text('file_name').notNull(),
    mime_type: text('mime_type').notNull(),
    size_bytes: integer('size_bytes').notNull(),
    width: integer('width'),
    height: integer('height'),
    alt_text: text('alt_text'),
    ai_caption: text('ai_caption'),
    folder: text('folder'),
    ...timestamps,
  },
  (t) => ({
    site_idx: index('site_media_site_idx').on(t.site_id),
    customer_idx: index('site_media_customer_idx').on(t.customer_id),
    folder_idx: index('site_media_folder_idx').on(t.site_id, t.folder),
    r2_unique: uniqueIndex('site_media_r2_unique').on(t.r2_key),
  }),
);

// ─── Blog posts ──────────────────────────────────────────────────────────────

export const sitePosts = sqliteTable(
  'site_posts',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    slug: text('slug').notNull(),
    title: text('title').notNull(),
    excerpt: text('excerpt'),
    content_md: text('content_md').notNull().default(''),
    content_html: text('content_html'), // rendered cache; regenerated on save
    cover_media_id: text('cover_media_id').references(() => siteMedia.id, {
      onDelete: 'set null',
    }),
    category: text('category'),
    tags_json: text('tags_json').notNull().default('[]'),
    author_name: text('author_name').notNull(),
    status: text('status', { enum: ['draft', 'published', 'scheduled', 'archived'] })
      .notNull()
      .default('draft'),
    scheduled_for: integer('scheduled_for', { mode: 'timestamp' }),
    published_at: integer('published_at', { mode: 'timestamp' }),
    seo_title: text('seo_title'),
    seo_description: text('seo_description'),
    view_count: integer('view_count').notNull().default(0),
    ...timestamps,
  },
  (t) => ({
    site_idx: index('site_posts_site_idx').on(t.site_id),
    customer_idx: index('site_posts_customer_idx').on(t.customer_id),
    slug_unique: uniqueIndex('site_posts_site_slug_unique').on(t.site_id, t.slug),
    status_idx: index('site_posts_status_idx').on(t.status),
    published_idx: index('site_posts_published_idx').on(t.published_at),
  }),
);

// ─── Forms ───────────────────────────────────────────────────────────────────
// `fields_json` is an array of field defs like:
//   { id, type:'email', label, required, options? }
// `settings_json` holds submit button text, success message, notify email list,
// optional webhook, Turnstile site key flag.

export const siteForms = sqliteTable(
  'site_forms',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    fields_json: text('fields_json').notNull().default('[]'),
    settings_json: text('settings_json').notNull().default('{}'),
    submission_count: integer('submission_count').notNull().default(0),
    is_active: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    ...timestamps,
  },
  (t) => ({
    site_idx: index('site_forms_site_idx').on(t.site_id),
    customer_idx: index('site_forms_customer_idx').on(t.customer_id),
    slug_unique: uniqueIndex('site_forms_site_slug_unique').on(t.site_id, t.slug),
  }),
);

export const siteFormSubmissions = sqliteTable(
  'site_form_submissions',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    form_id: text('form_id')
      .notNull()
      .references(() => siteForms.id, { onDelete: 'cascade' }),
    data_json: text('data_json').notNull(),
    ip_address: text('ip_address'),
    user_agent: text('user_agent'),
    referrer: text('referrer'),
    contact_id: text('contact_id'), // set after dedupe against site_contacts
    created_at: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (t) => ({
    form_idx: index('site_form_submissions_form_idx').on(t.form_id),
    site_idx: index('site_form_submissions_site_idx').on(t.site_id),
    created_idx: index('site_form_submissions_created_idx').on(t.created_at),
    contact_idx: index('site_form_submissions_contact_idx').on(t.contact_id),
  }),
);

// ─── Contacts (per-site CRM) ─────────────────────────────────────────────────
// These are the *site visitors / buyers / subscribers*, NOT hostdaddy customers.
// One site_contacts row per (site_id, email).

export const siteContacts = sqliteTable(
  'site_contacts',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    email: text('email').notNull(),
    name: text('name'),
    phone: text('phone'),
    company: text('company'),
    country: text('country'),
    source: text('source').notNull(), // 'form:<slug>', 'newsletter', 'order', 'chat', 'import'
    tags_json: text('tags_json').notNull().default('[]'),
    ltv_cents: integer('ltv_cents').notNull().default(0), // MYR cents
    order_count: integer('order_count').notNull().default(0),
    last_seen_at: integer('last_seen_at', { mode: 'timestamp' }),
    unsubscribed_at: integer('unsubscribed_at', { mode: 'timestamp' }),
    notes: text('notes'),
    ...timestamps,
  },
  (t) => ({
    site_idx: index('site_contacts_site_idx').on(t.site_id),
    customer_idx: index('site_contacts_customer_idx').on(t.customer_id),
    email_unique: uniqueIndex('site_contacts_site_email_unique').on(t.site_id, t.email),
    source_idx: index('site_contacts_source_idx').on(t.source),
    ltv_idx: index('site_contacts_ltv_idx').on(t.ltv_cents),
  }),
);

// ─── E-commerce: products ────────────────────────────────────────────────────

export const siteProducts = sqliteTable(
  'site_products',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    description_md: text('description_md'),
    type: text('type', { enum: ['physical', 'digital', 'service', 'subscription'] })
      .notNull()
      .default('digital'),
    price_cents: integer('price_cents').notNull(),
    compare_at_cents: integer('compare_at_cents'), // strikethrough price
    currency: text('currency').notNull().default('MYR'),
    cover_media_id: text('cover_media_id').references(() => siteMedia.id, {
      onDelete: 'set null',
    }),
    gallery_media_json: text('gallery_media_json').notNull().default('[]'),
    inventory_qty: integer('inventory_qty'), // null = unlimited
    track_inventory: integer('track_inventory', { mode: 'boolean' })
      .notNull()
      .default(false),
    variants_json: text('variants_json'), // JSON when product has variants
    weight_grams: integer('weight_grams'), // for shipping calculations
    sku: text('sku'),
    status: text('status', { enum: ['active', 'draft', 'archived'] })
      .notNull()
      .default('draft'),
    featured: integer('featured', { mode: 'boolean' }).notNull().default(false),
    sold_count: integer('sold_count').notNull().default(0),
    ...timestamps,
  },
  (t) => ({
    site_idx: index('site_products_site_idx').on(t.site_id),
    customer_idx: index('site_products_customer_idx').on(t.customer_id),
    slug_unique: uniqueIndex('site_products_site_slug_unique').on(t.site_id, t.slug),
    status_idx: index('site_products_status_idx').on(t.status),
    featured_idx: index('site_products_featured_idx').on(t.featured),
  }),
);

// ─── E-commerce: orders ──────────────────────────────────────────────────────
// Distinct from `invoices` in schema.ts which bills the *hostdaddy customer*
// for their hosting plan. site_orders bill the *end customer* buying from
// the customer's site.

export const siteOrders = sqliteTable(
  'site_orders',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    order_number: text('order_number').notNull(), // e.g. CFZ-2026-0001
    end_contact_id: text('end_contact_id').references(() => siteContacts.id, {
      onDelete: 'set null',
    }),
    end_customer_email: text('end_customer_email').notNull(),
    end_customer_name: text('end_customer_name').notNull(),
    end_customer_phone: text('end_customer_phone'),
    shipping_address_json: text('shipping_address_json'),
    billing_address_json: text('billing_address_json'),
    items_json: text('items_json').notNull(), // snapshot of items at order time
    subtotal_cents: integer('subtotal_cents').notNull(),
    tax_cents: integer('tax_cents').notNull().default(0),
    shipping_cents: integer('shipping_cents').notNull().default(0),
    discount_cents: integer('discount_cents').notNull().default(0),
    total_cents: integer('total_cents').notNull(),
    currency: text('currency').notNull().default('MYR'),
    discount_code: text('discount_code'),
    payment_provider: text('payment_provider', {
      enum: ['stripe', 'billplz', 'manual'],
    }),
    payment_status: text('payment_status', {
      enum: ['pending', 'paid', 'failed', 'refunded', 'partial_refund'],
    })
      .notNull()
      .default('pending'),
    fulfillment_status: text('fulfillment_status', {
      enum: ['unfulfilled', 'processing', 'shipped', 'delivered', 'cancelled'],
    })
      .notNull()
      .default('unfulfilled'),
    stripe_session_id: text('stripe_session_id'),
    billplz_bill_id: text('billplz_bill_id'),
    tracking_number: text('tracking_number'),
    tracking_carrier: text('tracking_carrier'),
    notes: text('notes'),
    paid_at: integer('paid_at', { mode: 'timestamp' }),
    shipped_at: integer('shipped_at', { mode: 'timestamp' }),
    ...timestamps,
  },
  (t) => ({
    site_idx: index('site_orders_site_idx').on(t.site_id),
    customer_idx: index('site_orders_customer_idx').on(t.customer_id),
    order_number_unique: uniqueIndex('site_orders_number_unique').on(
      t.site_id,
      t.order_number,
    ),
    payment_status_idx: index('site_orders_payment_status_idx').on(t.payment_status),
    fulfillment_idx: index('site_orders_fulfillment_idx').on(t.fulfillment_status),
    email_idx: index('site_orders_email_idx').on(t.end_customer_email),
    contact_idx: index('site_orders_contact_idx').on(t.end_contact_id),
  }),
);

// ─── Discount codes ──────────────────────────────────────────────────────────

export const siteDiscounts = sqliteTable(
  'site_discounts',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    code: text('code').notNull(),
    type: text('type', { enum: ['percent', 'fixed', 'free_shipping'] }).notNull(),
    value: integer('value').notNull(), // percent (0-100) or fixed cents
    min_subtotal_cents: integer('min_subtotal_cents'),
    max_uses: integer('max_uses'),
    used_count: integer('used_count').notNull().default(0),
    expires_at: integer('expires_at', { mode: 'timestamp' }),
    is_active: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    ...timestamps,
  },
  (t) => ({
    site_idx: index('site_discounts_site_idx').on(t.site_id),
    code_unique: uniqueIndex('site_discounts_site_code_unique').on(t.site_id, t.code),
  }),
);

// ─── Email marketing: campaigns ──────────────────────────────────────────────

export const siteEmailCampaigns = sqliteTable(
  'site_email_campaigns',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    subject: text('subject').notNull(),
    preheader: text('preheader'),
    body_html: text('body_html').notNull(),
    body_md: text('body_md'),
    from_name: text('from_name').notNull(),
    from_email: text('from_email').notNull(),
    reply_to: text('reply_to'),
    segment_json: text('segment_json'), // filter criteria over site_contacts
    status: text('status', {
      enum: ['draft', 'scheduled', 'sending', 'sent', 'paused', 'cancelled'],
    })
      .notNull()
      .default('draft'),
    scheduled_for: integer('scheduled_for', { mode: 'timestamp' }),
    sent_at: integer('sent_at', { mode: 'timestamp' }),
    sent_count: integer('sent_count').notNull().default(0),
    delivered_count: integer('delivered_count').notNull().default(0),
    open_count: integer('open_count').notNull().default(0),
    click_count: integer('click_count').notNull().default(0),
    bounce_count: integer('bounce_count').notNull().default(0),
    unsubscribe_count: integer('unsubscribe_count').notNull().default(0),
    ...timestamps,
  },
  (t) => ({
    site_idx: index('site_email_campaigns_site_idx').on(t.site_id),
    customer_idx: index('site_email_campaigns_customer_idx').on(t.customer_id),
    status_idx: index('site_email_campaigns_status_idx').on(t.status),
  }),
);

// ─── Email marketing: automations ────────────────────────────────────────────

export const siteEmailAutomations = sqliteTable(
  'site_email_automations',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    trigger: text('trigger', {
      enum: [
        'subscriber.new',
        'cart.abandoned',
        'order.placed',
        'order.fulfilled',
        'inactive.60d',
        'birthday',
        'manual',
      ],
    }).notNull(),
    steps_json: text('steps_json').notNull().default('[]'), // [{ delay_hours, subject, body, ... }]
    is_active: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    enrolled_count: integer('enrolled_count').notNull().default(0),
    completed_count: integer('completed_count').notNull().default(0),
    ...timestamps,
  },
  (t) => ({
    site_idx: index('site_email_automations_site_idx').on(t.site_id),
    customer_idx: index('site_email_automations_customer_idx').on(t.customer_id),
    trigger_idx: index('site_email_automations_trigger_idx').on(t.trigger),
  }),
);

// ─── Visitor chat conversations ──────────────────────────────────────────────

export const siteChatConversations = sqliteTable(
  'site_chat_conversations',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    visitor_id: text('visitor_id').notNull(), // anonymous fingerprint cookie
    contact_id: text('contact_id').references(() => siteContacts.id, {
      onDelete: 'set null',
    }),
    messages_json: text('messages_json').notNull().default('[]'),
    captured_email: text('captured_email'),
    page_url: text('page_url'),
    referrer: text('referrer'),
    status: text('status', { enum: ['active', 'closed', 'abandoned'] })
      .notNull()
      .default('active'),
    resolution: text('resolution', {
      enum: ['auto', 'lead_captured', 'call_booked', 'human_handoff', 'no_answer'],
    }),
    tokens_used: integer('tokens_used').notNull().default(0),
    ...timestamps,
  },
  (t) => ({
    site_idx: index('site_chat_site_idx').on(t.site_id),
    customer_idx: index('site_chat_customer_idx').on(t.customer_id),
    visitor_idx: index('site_chat_visitor_idx').on(t.visitor_id),
    contact_idx: index('site_chat_contact_idx').on(t.contact_id),
    status_idx: index('site_chat_status_idx').on(t.status),
  }),
);

// ─── AI agent runs (audit trail) ─────────────────────────────────────────────
// Every Build-mode AI agent invocation is logged here for cost tracking,
// undo/replay, and customer transparency.

export const siteAiRuns = sqliteTable(
  'site_ai_runs',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    agent: text('agent', {
      enum: ['build', 'seo', 'copy', 'image', 'visitor_chat', 'email_writer'],
    }).notNull(),
    prompt: text('prompt').notNull(),
    tool_calls_json: text('tool_calls_json').notNull().default('[]'),
    result_summary: text('result_summary'),
    success: integer('success', { mode: 'boolean' }).notNull().default(true),
    duration_ms: integer('duration_ms').notNull().default(0),
    tokens_input: integer('tokens_input').notNull().default(0),
    tokens_output: integer('tokens_output').notNull().default(0),
    cost_cents: integer('cost_cents').notNull().default(0),
    model: text('model').notNull(),
    snapshot_id: text('snapshot_id'), // for undo — points to a row in site_versions
    created_at: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (t) => ({
    site_idx: index('site_ai_runs_site_idx').on(t.site_id),
    customer_idx: index('site_ai_runs_customer_idx').on(t.customer_id),
    agent_idx: index('site_ai_runs_agent_idx').on(t.agent),
    created_idx: index('site_ai_runs_created_idx').on(t.created_at),
  }),
);

// ─── Version snapshots (one-click undo / restore) ────────────────────────────
// Stores a full snapshot of a page's content_json at a point in time. Used
// when the AI agent or human is about to make a destructive change.

export const siteVersions = sqliteTable(
  'site_versions',
  {
    id: id(),
    customer_id: text('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    site_id: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    page_id: text('page_id').references(() => sitePages.id, { onDelete: 'cascade' }),
    label: text('label').notNull(), // "Before AI rewrite", "Manual save"
    actor: text('actor').notNull(), // 'customer' | 'ai:<agent>' | 'system'
    content_snapshot_json: text('content_snapshot_json').notNull(),
    created_at: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (t) => ({
    site_idx: index('site_versions_site_idx').on(t.site_id),
    page_idx: index('site_versions_page_idx').on(t.page_id),
    created_idx: index('site_versions_created_idx').on(t.created_at),
  }),
);

// ─── Type exports ────────────────────────────────────────────────────────────

export type SitePage = typeof sitePages.$inferSelect;
export type NewSitePage = typeof sitePages.$inferInsert;
export type SiteMedia = typeof siteMedia.$inferSelect;
export type NewSiteMedia = typeof siteMedia.$inferInsert;
export type SitePost = typeof sitePosts.$inferSelect;
export type NewSitePost = typeof sitePosts.$inferInsert;
export type SiteForm = typeof siteForms.$inferSelect;
export type NewSiteForm = typeof siteForms.$inferInsert;
export type SiteFormSubmission = typeof siteFormSubmissions.$inferSelect;
export type NewSiteFormSubmission = typeof siteFormSubmissions.$inferInsert;
export type SiteContact = typeof siteContacts.$inferSelect;
export type NewSiteContact = typeof siteContacts.$inferInsert;
export type SiteProduct = typeof siteProducts.$inferSelect;
export type NewSiteProduct = typeof siteProducts.$inferInsert;
export type SiteOrder = typeof siteOrders.$inferSelect;
export type NewSiteOrder = typeof siteOrders.$inferInsert;
export type SiteDiscount = typeof siteDiscounts.$inferSelect;
export type NewSiteDiscount = typeof siteDiscounts.$inferInsert;
export type SiteEmailCampaign = typeof siteEmailCampaigns.$inferSelect;
export type NewSiteEmailCampaign = typeof siteEmailCampaigns.$inferInsert;
export type SiteEmailAutomation = typeof siteEmailAutomations.$inferSelect;
export type NewSiteEmailAutomation = typeof siteEmailAutomations.$inferInsert;
export type SiteChatConversation = typeof siteChatConversations.$inferSelect;
export type NewSiteChatConversation = typeof siteChatConversations.$inferInsert;
export type SiteAiRun = typeof siteAiRuns.$inferSelect;
export type NewSiteAiRun = typeof siteAiRuns.$inferInsert;
export type SiteVersion = typeof siteVersions.$inferSelect;
export type NewSiteVersion = typeof siteVersions.$inferInsert;
