-- Sites content schema — Phase A of the Sites module.
-- Adds the visual builder, blog, e-commerce, forms, contacts, email marketing,
-- visitor chat, AI agent audit log, and version history on top of the
-- existing `sites` deployment table.
--
-- Generated by hand to match packages/db/src/sites-content.ts
-- (drizzle-kit on Linux ran into a darwin-arm64 esbuild binary; regenerate
-- the snapshot on macOS with `pnpm db:generate` once for tidy diffs).

CREATE TABLE `site_pages` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`slug` text NOT NULL,
	`title` text NOT NULL,
	`content_json` text DEFAULT '{"sections":[]}' NOT NULL,
	`seo_title` text,
	`seo_description` text,
	`seo_og_image` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`is_home` integer DEFAULT false NOT NULL,
	`published_at` integer,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `site_media` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`r2_key` text NOT NULL,
	`file_name` text NOT NULL,
	`mime_type` text NOT NULL,
	`size_bytes` integer NOT NULL,
	`width` integer,
	`height` integer,
	`alt_text` text,
	`ai_caption` text,
	`folder` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `site_posts` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`slug` text NOT NULL,
	`title` text NOT NULL,
	`excerpt` text,
	`content_md` text DEFAULT '' NOT NULL,
	`content_html` text,
	`cover_media_id` text,
	`category` text,
	`tags_json` text DEFAULT '[]' NOT NULL,
	`author_name` text NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`scheduled_for` integer,
	`published_at` integer,
	`seo_title` text,
	`seo_description` text,
	`view_count` integer DEFAULT 0 NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`cover_media_id`) REFERENCES `site_media`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `site_forms` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`name` text NOT NULL,
	`slug` text NOT NULL,
	`fields_json` text DEFAULT '[]' NOT NULL,
	`settings_json` text DEFAULT '{}' NOT NULL,
	`submission_count` integer DEFAULT 0 NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `site_form_submissions` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`form_id` text NOT NULL,
	`data_json` text NOT NULL,
	`ip_address` text,
	`user_agent` text,
	`referrer` text,
	`contact_id` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`form_id`) REFERENCES `site_forms`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `site_contacts` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`email` text NOT NULL,
	`name` text,
	`phone` text,
	`company` text,
	`country` text,
	`source` text NOT NULL,
	`tags_json` text DEFAULT '[]' NOT NULL,
	`ltv_cents` integer DEFAULT 0 NOT NULL,
	`order_count` integer DEFAULT 0 NOT NULL,
	`last_seen_at` integer,
	`unsubscribed_at` integer,
	`notes` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `site_products` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`name` text NOT NULL,
	`slug` text NOT NULL,
	`description_md` text,
	`type` text DEFAULT 'digital' NOT NULL,
	`price_cents` integer NOT NULL,
	`compare_at_cents` integer,
	`currency` text DEFAULT 'MYR' NOT NULL,
	`cover_media_id` text,
	`gallery_media_json` text DEFAULT '[]' NOT NULL,
	`inventory_qty` integer,
	`track_inventory` integer DEFAULT false NOT NULL,
	`variants_json` text,
	`weight_grams` integer,
	`sku` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`featured` integer DEFAULT false NOT NULL,
	`sold_count` integer DEFAULT 0 NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`cover_media_id`) REFERENCES `site_media`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `site_orders` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`order_number` text NOT NULL,
	`end_contact_id` text,
	`end_customer_email` text NOT NULL,
	`end_customer_name` text NOT NULL,
	`end_customer_phone` text,
	`shipping_address_json` text,
	`billing_address_json` text,
	`items_json` text NOT NULL,
	`subtotal_cents` integer NOT NULL,
	`tax_cents` integer DEFAULT 0 NOT NULL,
	`shipping_cents` integer DEFAULT 0 NOT NULL,
	`discount_cents` integer DEFAULT 0 NOT NULL,
	`total_cents` integer NOT NULL,
	`currency` text DEFAULT 'MYR' NOT NULL,
	`discount_code` text,
	`payment_provider` text,
	`payment_status` text DEFAULT 'pending' NOT NULL,
	`fulfillment_status` text DEFAULT 'unfulfilled' NOT NULL,
	`stripe_session_id` text,
	`billplz_bill_id` text,
	`tracking_number` text,
	`tracking_carrier` text,
	`notes` text,
	`paid_at` integer,
	`shipped_at` integer,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`end_contact_id`) REFERENCES `site_contacts`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `site_discounts` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`code` text NOT NULL,
	`type` text NOT NULL,
	`value` integer NOT NULL,
	`min_subtotal_cents` integer,
	`max_uses` integer,
	`used_count` integer DEFAULT 0 NOT NULL,
	`expires_at` integer,
	`is_active` integer DEFAULT true NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `site_email_campaigns` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`name` text NOT NULL,
	`subject` text NOT NULL,
	`preheader` text,
	`body_html` text NOT NULL,
	`body_md` text,
	`from_name` text NOT NULL,
	`from_email` text NOT NULL,
	`reply_to` text,
	`segment_json` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`scheduled_for` integer,
	`sent_at` integer,
	`sent_count` integer DEFAULT 0 NOT NULL,
	`delivered_count` integer DEFAULT 0 NOT NULL,
	`open_count` integer DEFAULT 0 NOT NULL,
	`click_count` integer DEFAULT 0 NOT NULL,
	`bounce_count` integer DEFAULT 0 NOT NULL,
	`unsubscribe_count` integer DEFAULT 0 NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `site_email_automations` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`name` text NOT NULL,
	`trigger` text NOT NULL,
	`steps_json` text DEFAULT '[]' NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`enrolled_count` integer DEFAULT 0 NOT NULL,
	`completed_count` integer DEFAULT 0 NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `site_chat_conversations` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`visitor_id` text NOT NULL,
	`contact_id` text,
	`messages_json` text DEFAULT '[]' NOT NULL,
	`captured_email` text,
	`page_url` text,
	`referrer` text,
	`status` text DEFAULT 'active' NOT NULL,
	`resolution` text,
	`tokens_used` integer DEFAULT 0 NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`contact_id`) REFERENCES `site_contacts`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `site_versions` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`page_id` text,
	`label` text NOT NULL,
	`actor` text NOT NULL,
	`content_snapshot_json` text NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`page_id`) REFERENCES `site_pages`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `site_ai_runs` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`site_id` text NOT NULL,
	`agent` text NOT NULL,
	`prompt` text NOT NULL,
	`tool_calls_json` text DEFAULT '[]' NOT NULL,
	`result_summary` text,
	`success` integer DEFAULT true NOT NULL,
	`duration_ms` integer DEFAULT 0 NOT NULL,
	`tokens_input` integer DEFAULT 0 NOT NULL,
	`tokens_output` integer DEFAULT 0 NOT NULL,
	`cost_cents` integer DEFAULT 0 NOT NULL,
	`model` text NOT NULL,
	`snapshot_id` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
-- ─── Indexes ─────────────────────────────────────────────────────────────────
CREATE INDEX `site_pages_site_idx` ON `site_pages` (`site_id`);--> statement-breakpoint
CREATE INDEX `site_pages_customer_idx` ON `site_pages` (`customer_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `site_pages_site_slug_unique` ON `site_pages` (`site_id`,`slug`);--> statement-breakpoint
CREATE INDEX `site_pages_status_idx` ON `site_pages` (`status`);--> statement-breakpoint
CREATE INDEX `site_media_site_idx` ON `site_media` (`site_id`);--> statement-breakpoint
CREATE INDEX `site_media_customer_idx` ON `site_media` (`customer_id`);--> statement-breakpoint
CREATE INDEX `site_media_folder_idx` ON `site_media` (`site_id`,`folder`);--> statement-breakpoint
CREATE UNIQUE INDEX `site_media_r2_unique` ON `site_media` (`r2_key`);--> statement-breakpoint
CREATE INDEX `site_posts_site_idx` ON `site_posts` (`site_id`);--> statement-breakpoint
CREATE INDEX `site_posts_customer_idx` ON `site_posts` (`customer_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `site_posts_site_slug_unique` ON `site_posts` (`site_id`,`slug`);--> statement-breakpoint
CREATE INDEX `site_posts_status_idx` ON `site_posts` (`status`);--> statement-breakpoint
CREATE INDEX `site_posts_published_idx` ON `site_posts` (`published_at`);--> statement-breakpoint
CREATE INDEX `site_forms_site_idx` ON `site_forms` (`site_id`);--> statement-breakpoint
CREATE INDEX `site_forms_customer_idx` ON `site_forms` (`customer_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `site_forms_site_slug_unique` ON `site_forms` (`site_id`,`slug`);--> statement-breakpoint
CREATE INDEX `site_form_submissions_form_idx` ON `site_form_submissions` (`form_id`);--> statement-breakpoint
CREATE INDEX `site_form_submissions_site_idx` ON `site_form_submissions` (`site_id`);--> statement-breakpoint
CREATE INDEX `site_form_submissions_created_idx` ON `site_form_submissions` (`created_at`);--> statement-breakpoint
CREATE INDEX `site_form_submissions_contact_idx` ON `site_form_submissions` (`contact_id`);--> statement-breakpoint
CREATE INDEX `site_contacts_site_idx` ON `site_contacts` (`site_id`);--> statement-breakpoint
CREATE INDEX `site_contacts_customer_idx` ON `site_contacts` (`customer_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `site_contacts_site_email_unique` ON `site_contacts` (`site_id`,`email`);--> statement-breakpoint
CREATE INDEX `site_contacts_source_idx` ON `site_contacts` (`source`);--> statement-breakpoint
CREATE INDEX `site_contacts_ltv_idx` ON `site_contacts` (`ltv_cents`);--> statement-breakpoint
CREATE INDEX `site_products_site_idx` ON `site_products` (`site_id`);--> statement-breakpoint
CREATE INDEX `site_products_customer_idx` ON `site_products` (`customer_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `site_products_site_slug_unique` ON `site_products` (`site_id`,`slug`);--> statement-breakpoint
CREATE INDEX `site_products_status_idx` ON `site_products` (`status`);--> statement-breakpoint
CREATE INDEX `site_products_featured_idx` ON `site_products` (`featured`);--> statement-breakpoint
CREATE INDEX `site_orders_site_idx` ON `site_orders` (`site_id`);--> statement-breakpoint
CREATE INDEX `site_orders_customer_idx` ON `site_orders` (`customer_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `site_orders_number_unique` ON `site_orders` (`site_id`,`order_number`);--> statement-breakpoint
CREATE INDEX `site_orders_payment_status_idx` ON `site_orders` (`payment_status`);--> statement-breakpoint
CREATE INDEX `site_orders_fulfillment_idx` ON `site_orders` (`fulfillment_status`);--> statement-breakpoint
CREATE INDEX `site_orders_email_idx` ON `site_orders` (`end_customer_email`);--> statement-breakpoint
CREATE INDEX `site_orders_contact_idx` ON `site_orders` (`end_contact_id`);--> statement-breakpoint
CREATE INDEX `site_discounts_site_idx` ON `site_discounts` (`site_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `site_discounts_site_code_unique` ON `site_discounts` (`site_id`,`code`);--> statement-breakpoint
CREATE INDEX `site_email_campaigns_site_idx` ON `site_email_campaigns` (`site_id`);--> statement-breakpoint
CREATE INDEX `site_email_campaigns_customer_idx` ON `site_email_campaigns` (`customer_id`);--> statement-breakpoint
CREATE INDEX `site_email_campaigns_status_idx` ON `site_email_campaigns` (`status`);--> statement-breakpoint
CREATE INDEX `site_email_automations_site_idx` ON `site_email_automations` (`site_id`);--> statement-breakpoint
CREATE INDEX `site_email_automations_customer_idx` ON `site_email_automations` (`customer_id`);--> statement-breakpoint
CREATE INDEX `site_email_automations_trigger_idx` ON `site_email_automations` (`trigger`);--> statement-breakpoint
CREATE INDEX `site_chat_site_idx` ON `site_chat_conversations` (`site_id`);--> statement-breakpoint
CREATE INDEX `site_chat_customer_idx` ON `site_chat_conversations` (`customer_id`);--> statement-breakpoint
CREATE INDEX `site_chat_visitor_idx` ON `site_chat_conversations` (`visitor_id`);--> statement-breakpoint
CREATE INDEX `site_chat_contact_idx` ON `site_chat_conversations` (`contact_id`);--> statement-breakpoint
CREATE INDEX `site_chat_status_idx` ON `site_chat_conversations` (`status`);--> statement-breakpoint
CREATE INDEX `site_versions_site_idx` ON `site_versions` (`site_id`);--> statement-breakpoint
CREATE INDEX `site_versions_page_idx` ON `site_versions` (`page_id`);--> statement-breakpoint
CREATE INDEX `site_versions_created_idx` ON `site_versions` (`created_at`);--> statement-breakpoint
CREATE INDEX `site_ai_runs_site_idx` ON `site_ai_runs` (`site_id`);--> statement-breakpoint
CREATE INDEX `site_ai_runs_customer_idx` ON `site_ai_runs` (`customer_id`);--> statement-breakpoint
CREATE INDEX `site_ai_runs_agent_idx` ON `site_ai_runs` (`agent`);--> statement-breakpoint
CREATE INDEX `site_ai_runs_created_idx` ON `site_ai_runs` (`created_at`);
